In [1]:
import numpy as np

In [2]:
A = np.matrix(np.random.random((5,5)))

In [3]:
print(A)

[[0.86964951 0.47071166 0.17278015 0.19223469 0.12859546]
 [0.89456332 0.7025513  0.31957471 0.42431916 0.03342263]
 [0.01620137 0.267075   0.95819584 0.14934392 0.20072514]
 [0.6365238  0.15748714 0.28573411 0.52642199 0.21197146]
 [0.47032906 0.11785669 0.98263895 0.21271343 0.20560759]]


In [5]:
test = np.matrix([5,5,5])

In [6]:
from scipy import linalg, sparse

In [ ]:
A = np.

In [ ]:
A.

In [ ]:
x = numpy.random.rand(5)
x

In [ ]:
b = np.dot(A,x)

In [ ]:
b

In [ ]:
import numpy.linalg as LA

In [ ]:
x = LA.solve(A,b)

In [ ]:
x

In [ ]:
A = numpy.eye(3)
A

In [ ]:
bob = np.matrix('1 2;3 4')

In [ ]:
bob

In [ ]:
y = np.array([1,2,3])

In [ ]:
y